version: '3.8'
services:
    www:
        container_name: www_lmb
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - ./www:/var/www/html
        ports:
            - 8180:80
    mysql:
        container_name: mysql_lmb
        image: mysql/mysql-server:5.5
        ports:
            - 3386:3306
        environment:
            MYSQL_DATABASE: 'tapisserie'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: "tapisserie"
            MYSQL_ROOT_PASSWORD: "tapisserie"
            #MYSQL_ROOT_HOST: "%"
        volumes:
            - ./data/mysql:/var/lib/mysql    
networks:
    default:
        external:
            name: network-lmb